name: Staging

on:
  push:
    branches:
      - staging
      - FEAT-*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages & build ssr/prod ng app
        run: |
          npm install
          npm run build:prod
          ls
          cd dist
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-folder
          path: |
            dist/widesign-eltonwhybrow

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: dist-folder

      - name: Where am i
        run: |
          ls
          pwd

      - name: Upload
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ftp://ftps3.uk.cloudlogin.co
          ftp_username: ${{ secrets.FTP_USER }}
          ftp_password: ${{ secrets.FTP_PWD }}
          local_source_dir: "/github/workspace/"
          dist_target_dir: "/"
          delete: "true"
          exclude: "'^.htaccess'"
          only_newer: true
          ignore_time: false
